name: coinsift_app
description: "Финансовое приложение с анализом расходов, калькуляторами и инвестициями"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  # State Management
  provider: ^6.1.1
  flutter_bloc: ^8.1.3

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  flutter_secure_storage: ^9.2.4

  # UI & Animations
  fl_chart: ^0.66.0
  animate_do: ^3.1.2
  lottie: ^3.0.0
  shimmer: ^3.0.0
  flutter_animate: ^4.3.0

  # Utils
  intl: ^0.19.0
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  flutter_svg: ^2.0.9
  http: ^1.2.0
  file_selector: ^1.0.3
  csv: ^6.0.0
  path: ^1.9.0
  url_launcher: ^6.2.5
  webview_flutter: ^4.8.0
  crypto: ^3.0.3

  # Charts
  syncfusion_flutter_charts: ^24.2.3
  percent_indicator: ^4.2.3

  # Forms & Validation
  flutter_form_builder: ^9.2.1

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
